### ISSUE TITLE
Null check operator used on a null value inside ListController.getOffsetToReveal

### ISSUE THREAD

**Issue by ekuleshov** [superlistapp/super_sliver_list#67]
Got this error from one of user devices running on iOS 17.5.1 and Flutter 3.22.3.
Not sure what is up with that as value is being asserted for null two times before this error is thrown.

```
TypeError: Null check operator used on a null value
  #0      ListController.getOffsetToReveal (package:super_sliver_list/src/super_sliver_list.dart:275)
  #1      ListController.jumpToItem (package:super_sliver_list/src/super_sliver_list.dart:93)
...
  #3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433)
...
  #10      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
  #11      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
  #12      _DelayedData.perform (dart:async/stream_impl.dart:541)
  #13      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
  #14      _PendingEvents.schedule.<fn> (dart:async/stream_impl.dart:617)
  #15      _microtaskLoop (dart:async/schedule_microtask.dart:40)
  #16      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

```

**Comment by ekuleshov** [comment]
Getting more of those from user's devices. Flutter 3.24.4 now and also on Android devices.

@knopp any clues how to debug this? Does this mean that the ExtentManager delegate is not set?

I'm somewhat puzzled that assertion on 274 pass but the non-null dereference on the next line is failing.

<img width="584" alt="image" src="https://github.com/user-attachments/assets/d9688b32-2fa6-48fe-84cf-d8d84b5dc396">

**Comment by xsahil03x** [comment]
Hey @ekuleshov, are you running the app in debug mode? As assertions don't work in profile and release mode.

**Comment by ekuleshov** [comment]
> Hey @ekuleshov, are you running the app in debug mode? As assertions don't work in profile and release mode.

Unlikely. This stack trace is from a user device with app installed from the app store.
